### ISSUE TITLE
Foundation.js in HTML & JS

### ISSUE THREAD

**Issue by borchy37** [juliancwirko/meteor-zf5#11]
Hey @juliancwirko ,

Could you by any chance provide HTML & JS sourcecode of your demo on Meteorpad or Codepen, to see how you've structured templates to work with Foundation js? Or maybe expand documentation on that subject for Meteor newbies?

Also, in original _settings.scss there is 
```@import 'foundation/functions';```
I guess that has to be commented out and taken care of differently?

I'll close the issue as soon as you see it. 
Tnx a million

**Comment by juliancwirko** [comment]
Hey, if you coppy settings.scss to you project folders you should use: `'{juliancwirko:zf5}/scss/foundation/functions;'` instead `@import 'foundation/functions';` I don't wanted to change original files in the package. I'll place it in the readme in more visible place.

I'll try to prepare some other examples. Because my example is very old. I don't want to show it ;)

Anyway, soon there will be Foundation 6 and probably official Meteor package by @Zurb :)

**Comment by borchy37** [comment]
OK, tnx @juliancwirko

**Comment by juliancwirko** [comment]
I reopen this one :) Just to remember. I'll prepare demo website.

**Comment by juliancwirko** [comment]
Ok here is a new demo page: https://zf5.meteor.com
And here is a source code: https://github.com/juliancwirko/meteor-zf5-demo
